name: Pylint

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint beautifulsoup4 requests

      - name: Analysing the code with pylint
        run: |
          Get-ChildItem -Path . -Filter *.py -Recurse | ForEach-Object { pylint $_.FullName --max-line-length=140 --disable=R0903 }
